# Change these first
owner: phpbb-fr-com # Your GitHub organization or username, where this repository lives
repo: status-site # The name of this repository

sites:
  - name: phpBB-fr.com
    url: https://www.phpbb-fr.com
  - name: Forum de démonstration
    url: https://demo.phpbb-fr.com
  - name: Base de connaissance
    url: http://forum.phpbb-fr.com
  - name: phpBB-fr DNS 1
    url: 51.254.27.129
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.phpbb-fr.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/phpbb-fr-com/status-site/master/assets/logophpbb-fr.png
  favicon: https://raw.githubusercontent.com/phpbb-fr-com/status-site/master/assets/favicon.ico
  theme: ocean
  name: Status Site
  introTitle: "Dernières actualités"
  introMessage: Ce site annonce les maintenances et l'état de santé des services de phpBB-fr.com
  navbar:
    - title: Accueil
      href: https://www.phpbb-fr.com
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
